### ISSUE TITLE
Would you be interested in pulling the changes I've made on my fork of your package ?

### ISSUE THREAD

**Issue by VicGUTT** [zachleigh/laravel-vue-generators#6]
I have made a few changes to the package ([see the changes here](https://github.com/zachleigh/laravel-vue-generators/commit/b88f9e03fb2d050d947946556250e1da88014dfd)). I think I've made it a bit more generic and added a "view" command as well as a "simple" flag. Would you be interested in me making a pull resquest ?

If yes I'll also update the Readme file and maybe put the default config paths back to "resources/...".

Anyway, thanks for the package :)

**Comment by zachleigh** [comment]
Hi @VicGUTT 
Thanks for the interest, but I've pretty much stopped development on this project. The vue cli has gotten much better since I made this and I personally have been using that and editor snippets instead of this package.
